name: InventoryClear
author: Jack Noordhuis
version: 2.0.0
description: Basic plugin that aloows you to view and clear a players inventory with ease.
main: \inventoryclear\Main
api: 2.0.0
     
permissions:
    inventoryclear.clearinv.other:
        description: Players with this permission are able to clear the Inventory of other Players
        default: op
        
    inventoryclear.clearinv.self:
        description: Players with this permission are able to clear their own Inventories
        default: true

    inventoryclear.viewinv:
        description: "Allows players to view other players' inventory's"
        default: true